In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', 500)

# Tables

In [3]:
orders = pd.read_csv('data/Orders.csv',index_col=0)
order_regions = pd.read_csv('data/OrderRegions.csv',index_col=0)
order_details = pd.read_csv('data/Order Details.csv',index_col=0)
products = pd.read_csv('data/Products.csv',index_col=0)
categories = pd.read_csv('data/Categories.csv',index_col=0)
shippers = pd.read_csv('data/Shippers.csv',index_col=0)
suppliers = pd.read_csv('data/Suppliers.csv',index_col=0)
customers = pd.read_csv('data/Customers.csv',index_col=0)

# Data Preparation

In [4]:
orders.drop(columns=['ShipRegion','ShipName','ShipAddress'],inplace=True)

In [5]:
products = products[['ProductID','SupplierID','CategoryID']]

In [6]:
order_details1 = pd.merge(order_details[['OrderID','ProductID']],products,left_on='ProductID',right_on='ProductID')

In [7]:
order_details1

      OrderID  ProductID  SupplierID  CategoryID
0       10248         11           5           4
1       10296         11           5           4
2       10327         11           5           4
3       10353         11           5           4
4       10365         11           5           4
5       10407         11           5           4
6       10434         11           5           4
7       10442         11           5           4
8       10443         11           5           4
9       10466         11           5           4
10      10486         11           5           4
11      10489         11           5           4
12      10528         11           5           4
13      10535         11           5           4
14      10542         11           5           4
15      10545         11           5           4
16      10553         11           5           4
17      10566         11           5           4
18      10570         11           5           4
19      10614         11           5           4
20      10637         11           5           4
21      10698         11           5           4
22      10726         11           5           4
23      10770         11           5           4
24      10797         11           5           4
25      10800         11           5           4
26      10823         11           5           4
27      10842         11           5           4
28      10862         11           5           4
29      10869         11           5           4
...       ...        ...         ...         ...
2201    10814         48          22           3
2202    10418         61          29           2
2203    10440         61          29           2
2204    10455         61          29           2
2205    10504         61          29           2
2206    10513         61          29           2
2207    10530         61          29           2
2208    10550         61          29           2
2209    10595         61          29           2
2210    10642         61          29           2
2211    10716         61          29           2
2212    10724         61          29           2
2213    10735         61          29           2
2214    10769         61          29           2
2215    10814         61          29           2
2216    10880         61          29           2
2217    10906         61          29           2
2218    10910         61          29           2
2219    10933         61          29           2
2220    10990         61          29           2
2221    10998         61          29           2
2222    11034         61          29           2
2223    11042         61          29           2
2224    11052         61          29           2
2225    11058         61          29           2
2226    10420          9           4           6
2227    10515          9           4           6
2228    10687          9           4           6
2229    10693          9           4           6
2230    10848          9           4           6

[2231 rows x 4 columns]

In [9]:
order_details2 = pd.get_dummies(order_details1, columns=['ProductID','CategoryID','SupplierID']).groupby(['OrderID'], as_index=False).sum()

In [12]:
final_df = pd.merge(orders,order_details2,left_on='OrderID',right_on='OrderID')

In [28]:
final_df = final_df.rename(columns={'EmployeeID':'EmployeeID:string','ShipVia':'ShipVia:string'})

In [33]:
final_df.to_csv('northwind_data.csv',index=False)