In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../datasets/Izenda_data_through_201712_ver_2.csv", low_memory=False)

In [3]:
print ("Initial number of rows and column: ", data.shape)
print ("Total memory used: {} MB".format(round(data.memory_usage().sum()/(1024*1024), 2)))

Initial number of rows and column:  (2171066, 14)
Total memory used: 231.89 MB

In [4]:
data.columns

Index(['LossYearMo', 'City', 'State', 'Zip', 'DivisionName', 'StartedFlag',
       'LossType', 'DisplayName', 'CommOrRes', 'NoteCount', 'PhotoCount',
       'JobCount', 'ClaimCount', 'EstimateTotal'],
      dtype='object')

### Analyzing NaN values

In [5]:
data.isna().sum()

LossYearMo             0
City               10024
State              16340
Zip                14110
DivisionName          84
StartedFlag            2
LossType         2083963
DisplayName            2
CommOrRes         331780
NoteCount           5338
PhotoCount             2
JobCount               3
ClaimCount             3
EstimateTotal          3
dtype: int64

### Drop columns with high null values

In [6]:
data1 = data.drop('LossType', axis=1)

### Drop Rows with null values

In [7]:
data1 = data1.dropna()

In [8]:
print ("Number of rows and column: ", data1.shape)
print ("Total memory used: {} MB".format(round(data1.memory_usage().sum()/(1024*1024), 2)))

Number of rows and column:  (1814705, 13)
Total memory used: 193.83 MB

In [9]:
data1.isna().sum()

LossYearMo       0
City             0
State            0
Zip              0
DivisionName     0
StartedFlag      0
DisplayName      0
CommOrRes        0
NoteCount        0
PhotoCount       0
JobCount         0
ClaimCount       0
EstimateTotal    0
dtype: int64

In [10]:
final_col_length = 0
for col in data1.columns:
    if col != 'EstimateTotal':
        print (col, ":", data1[col].nunique())
        final_col_length += data1[col].nunique()

print ("\nTotal columns: ", final_col_length)

LossYearMo : 212
City : 52550
State : 222
Zip : 312401
DivisionName : 2764
StartedFlag : 2
DisplayName : 17
CommOrRes : 655
NoteCount : 4716
PhotoCount : 1986
JobCount : 98
ClaimCount : 63

Total columns:  375686

In [22]:
final_col_length = 0
data2 = data.head(100000)
for col in data2.columns:
    if col != 'EstimateTotal':
        print (col, ":", data2[col].nunique())
        final_col_length += data2[col].nunique()

print ("\nTotal columns: ", final_col_length)

LossYearMo : 169
City : 14816
State : 95
Zip : 43201
DivisionName : 270
StartedFlag : 2
LossType : 49
DisplayName : 16
CommOrRes : 152
NoteCount : 1319
PhotoCount : 723
JobCount : 49
ClaimCount : 28

Total columns:  60889

### Converting categorical columns to One hot encoding

In [41]:
data.CommO.unique()

array([nan, 'Residential', 'Government', 'Tenant Policy', 'Commercial',
       '0', 'Insurance Residential', 'Governmental ',
       'Commercial - Rental Property', 'Multi-Family',
       'Commercial Large Loss', 'Residential Large Loss', 'Commercial ',
       'Water Damage', 'Fire Damage', 'Property Management',
       'Home Builder', 'Residential - Insurance',
       'Commercial - Insurance', 'Residential - Private',
       'Business/Residental', 'Industrial', 'Schools', 'Residential ',
       'Non-Applicable', 'School', 'R', 'Construction', 'Mold', 'SRM',
       'Water', 'Fire', 'Multi- Family Dwelling',
       'Condominium/Multi-Family', 'Hail', 'Wind', 'Vehicle Impact',
       'Consumer Service', 'Trauma', 'Vandalism', 'Multi-Family ',
       'Strata', 'residential', 'Multi-Family Large Loss', 'Tree',
       'Commerical', 'Private', 'Multi Family', 'Residential- Insurance',
       'Residential Program', 'Program', 'Commercial Program', 'Remodel',
       'Tribal Program', 'Healthcare', 'Resid', 'Governmental',
       'Educational', 'RÃ©sidentiel', 'Large Loss Commercial',
       'Property Managers', 'Condo', 'Multi- Family',
       'Religious Institution', 'Health Care/ Assisted Living', 'CCQ',
       'First Priority', ' Residential', 'Space ship', 'Military',
       'High-Rise', 'Pipe burst basement', '31510- Emergency Fire',
       'Residential - Allstate', 'SFPM Clients',
       'Residential - During Business Hours',
       'Residential - After Business Hours',
       'Commercial - After Business Hours',
       'Commercial - During Business Hours', 'Strata/Property Management',
       'Churches', 'Residential - Single Family', 'Hospitality - Hotel',
       'Evaluation Only', 'Maritime', 're', 'res', 'Condo Assoc.',
       'Hospital', 'Hotel', 'Hospitality Facilities',
       'Insurance Programs', 'Medical Facilities', 'Property Mgmt',
       'Apartment Complex', 'Dungeon', 'Ceptic Backup', 'HOA',
       'Residential / Multi-family', 'Preferred Agency Program',
       '--Select--', 'Schools K-12', 'College', 'Church',
       'Residential - Multi Family', 'Education - College',
       'Multi-unit Residential', 'Church/School', 'Treasure chest',
       'Trailer Park', 'rodent clean up',
       'Property Management - Residential', 'Commericial',
       'Banner Health Risk Management', 'Other Customer',
       'Banner Health Facility', 'ADD SUPPLY LEAD', 'Commerial',
       'Residential / Single ', 'Unknown', 'Commercial / Multi-Unit',
       'Arizona School District', 'Property Management - Commercial',
       'Residential / Multi-Unit', 'Insurance Res', 'Demolition',
       'County / Municipal', 'Residential - No Coverage',
       'Commercial - No Coverage', 'Multi-Family Residential', 'MRP',
       'ACT', 'Condominium', 'Hotel/Resort', 'Work Authorization',
       'Contract', 'Change Order- WA to Contract', 'Multi-family',
       'Semi-Critical', 'Single Family Residential',
       'Large Loss Commercial >25k', 'Critical', 'Residential`',
       'Property Management ', 'Multi Family Dwelling', 'mold', 'Sewage ',
       'Res', 'Biohazard', 'Residential-Homeowner', 'Residential-Renter',
       'Storm', '1', 'Apartment', 'Residential - Questionable',
       'Self Pay', 'Insurance', 'Residential- Self Pay',
       'Multi-Unit Residential', 'Large Loss Residential >25k',
       'Residentialw', 'Single Family Home', 'Commercial- Insurance',
       'Commercial- Self Pay', 'Direct Pay / No Program', 'SP Corporate',
       'Xactanalysis', 'Medical Facility', 'Multi-Family Dwelling',
       'Residential - Covered', 'Gun safe', 'Blizzard', 'Insured',
       'water intrusion', 'Commercial/Rsidential',
       'Residential Property Management', 'Multi-Family Dewelling', 'r',
       'Hazmat', 'Multi-Dwelling', 'Residential-Insurance',
       'Residential-Self Pay', 'Tribal', 'Insurer', 'Residentiald',
       'Non-Insurance Res', 'Insurance Comm', 'Non-Insurance Comm',
       'Non-Insurance Multi-Family', 'General Cleaning',
       'Post Construction Cleaning', 'Residential Large Loss >25K',
       'Residential X-Large Loss >75K', 'Madison Schools',
       'Condominium Building ', 'Commercial - Private',
       'Army North Service', 'Non-Critical', 'roof', 'Pack Out', 'Smoke',
       'pack out', 'WATER', 'Commercial / Single ', 'Expert Opinion',
       'Comp Estimate', 'City', 'HOA Management', 'Religious',
       'Multi Unit Condo', 'RÃ©sidentielle-Maison / Residential-Home',
       'RÃ©sidentielle-Syndicat / Residential-Syndicate',
       'Commerciale-Autre / Commercial-Other',
       'RÃ©sidentielle-Appartement / Residential-Apartment',
       'RÃ©sidentielle-AmÃ©liorations/Residential-Improvements',
       'Organisation Religieuse / Religious Organization',
       'Multi-Family Dwellings', 'Education', 'Resturant', 'Retail',
       'Office Facilities/ Mix Use', 'Hotel/ Resort', 'Office Facilities',
       'residental', 'RECONSTRCUTION', 'Educational Facility',
       'Multi-Family dwelling', 'Multi-Family Home', 'Church Property',
       'Managed Housing Facility', 'NEXXUS', 'ERP - Residential',
       'ASP - Residential', 'Large Loss Residential', 'Res/Com',
       'Condo/Apartment', 'Inspection Only', 'Cat 2',
       'EMS - Program TPAs', '7465', 'Schools ', 'MWF DIVISON',
       'Commercial - RENTAL', 'Multi-logements', 'Commerciale',
       'Residental', 'Insurance Commercial', 'Insurance Multi-Family',
       'Cat 3', 'Multi Family/Apartment/Condo',
       'Residential Carpet Cleaning ', 'Santa Clara - Com',
       'Contra Costa - Com', '31520 - Emergency Water',
       '31301 - Construction Repair', '31400 - HazMat',
       '31530 - Home Improvement', 'Condo Board', 'Program Job',
       'Xactimate', 'T&M', 'Warranty', 'Unknown / Pending', 'M',
       'Residential - Work Auth.', 'Commercial - Contract',
       'Commercial - Work Auth.', 'Residential - Contract', 'Sinkhole',
       'Roofing/Siding', 'Bio', 'Residential Apartments',
       'Residential Single Family', 'Hospital / Healthcare Facility',
       'SPP', 'Residential-Insurance Claim', 'Residential-HOA',
       'New Construction', 'Wind Damage', 'Residentialcar', 'adfada',
       'Builders', 'Owners Corporation', 'Nationwide MRP',
       'State Farm PSP', 'Nationwide ARP', 'Westfield MRP',
       'Nationwide MIT', 'Carpet Cleaning',
       'Mid Loss Repair $10 k to $50 k', 'Contractor Connection',
       'Non-Insurance Residential',
       'Multi-Family Dwelling (Apt Complexes)', 'Capital Region Housing',
       'Government ', 'Nexxus Residential', 'N/A-Plumber Accident',
       'mobile homes/floating homes', 'Assignment', 'EMS - MNT',
       'Medical', 'Residential - INS', 'Commercial1901', 'residential ',
       'Board up', 'Residential - CC', 'Non Profit',
       'Commerciale-Institution / Commercial-Institution',
       'Commerciale-HÃ´tel / Commercial-Hotel', 'RECON DIVISION',
       'Invitation Homes', 'SMS Assist', 'DR Residential', 'Condominiums',
       'ERP - Commercial', 'ASP - Commercial', 'Mixed Use Structure',
       'Commercial \t\t', 'sewage', 'Residentia', '6-13-17',
       'Residential Insurance', 'Agents', 'Residential-Non Insurance',
       'Builder', 'DPLS', 'Government/Municipality', 'Residemtial',
       'Commercialpo', 'Residential-INS', 'High-Rise (4+ Levels)',
       'Catastrophe', 'water', 'Assisted Living', 'Hospitality',
       'Residential - Self-Pay', 'Warranty Repair', 'Other',
       'Apartment Rehabilitation', 'Wind/Storm', '31700 Home Improvement',
       'Salt Lake', 'Ogden', 'Park City', 'Provo', 'Tooele', 'Misc',
       'Residence', 'Residential```', 'Category 1', 'Category 3',
       'Government Large Loss', 'Hard Bid', 'Multi-Unit', 'cellar',
       'Commercial - Insurance Pay', 'Residential - Insurance Pay',
       'Commercial - Self Pay', 'Residential - Self Pay', 'Maintance ',
       'Condominium Corporation ', 'Change Order - Contract to WA',
       'Residential - EMR', '`', 'Multifamily Dwelling',
       'District/School', 'Ashton Tiffany  LLC',
       'Commercial Large Loss >25K', 'Resedential', 'Residential      ',
       'Commercial - Questionable', 'Commercial - Covered',
       'Not Applicable', 'fire', 'Alacrity', 'Mulitfamily',
       'Condo/Duplex', 'Multi-Family (Condo / Apartment)',
       'Commercial & Residential', 'No Loss', 'Commercial - EMR',
       'Commercial - INS', 'Restaurant', 'UNITS', 'commercial',
       'Health Care', 'Institutional', 'Sewage Damage', 'Condominium ',
       'Mobile Home', 'Townhouse', 'FIRE', 'CRS', 'Penthouse',
       'High School', 'Repairs - Under $10 000',
       'Large Loss Repair - $50 k and up', 'Alameda - Res',
       'Santa Cruz - Res', 'Alameda - Com', 'PS-Residential',
       'Contra Costa - Res', 'Stanislaus-Res', 'Santa Clara - Res',
       'San Juaquin-Res', 'San Francisco-Ress', 'San Mateo-Reses', '2',
       'EMS - COM or Multi-Fam', 'Commercial Office', 'Condo / HOA',
       'Standing Purchase Order', 'BID - Request', 'High Rise',
       'COMMERCIAL', 'RESIDENTIAL', 'Municipality', 'Mutli-Family',
       'category 3 ', 'categroy 1 ', 'TPA', 'N/A- Septic Pumping',
       'Septic Pumping', 'Septic Pumping - Work Order',
       'Residential / Commercial', 'Cleaning', 'Emergency', 'CHURCH',
       'School/University', 'Bank/Financial', ' ', 'Residential+',
       'Public', 'Commercial Property Mgmt', 'DKI Commercial', 'IMACC',
       'trailer', 'Government/Military', 'Army South Service',
       'Residential - PG  MD', '31310 Construction - Water',
       'San Francisco-Comm', '31520 Emergency - Water', '31600 Contents',
       '31510 Emergency - Fire', '31600 - Contents', 'DKI',
       'Hickam Service', 'Marin - Res', 'San Mateo-Com',
       'Sacramento - Com', 'Solano-Res', 'Solano-Com', 'Army',
       'San Juaquin-Com', 'Santa Cruz - Com', 'San Mateo-Res', 'a',
       'Industrial/ Manufacturing', 'Industrial ',
       'Commercial Neighborhood Shopping', 'Townhome',
       'Commercial Financial', 'Industrial Storage',
       'Residential Mfg Home', 'Utility', 'Residential Condo',
       'Commercial Professional Services', 'Commercial Motel',
       'Industrial Manufacturing', 'Commercial Retail Shops and Stores',
       'CAT 3', 'ICE', 'Residentiall', '08142016', 'Warehouse', 'none',
       '31400 Hazmat', 'Medical Facilty', 'c', 'Fire/Smoke',
       'Marin - Com', 'Residential - RENTAL',
       'Billing Plumber- No Contract Signed', '31320 Construction - Fire',
       '31340 Construction - Remodel', 'ABM', 'Multifamily dwelling',
       'Biohazard ', 'Water ', 'Board-Up', 'Wind ', 'Hospitality ', 'RE',
       'Inspection', 'Estimate', 'Structure', 'Mold Remediation',
       'Cat 3 ', 'Mitigation ', 'Cat 3 Water from above ',
       'Water_Damage ', 'WRT', 'Residential - Innovation',
       'Residential - CCA/CSAA', 'Ladder Assist', 'Medical Facility ',
       'Marine', 'Contractor Connection-Residental ', '3/8/2017',
       'PS-Commercial', 'PS-Resorts', 'PS-Multi-Family',
       'Outside/Non-Insurance', 'Church/Religious ',
       'Hospitality/Hotel-Motel', 'Contractor', 'Mold ', 'Residentialr',
       'Car Accident', 'Multi-Family Non-Insurance',
       'Residential - Tenant/Landlord', 'Commercial Large loss',
       'Rental Property', 'Mould', '05/12/2017', 'Army North COM', 'pd',
       '1 - Clean Water', '3 - Black Water',
       'Contractor Connection- Commercial', 'Business Development',
       '31100 Carpet Cleaning', 'School/ University', 'Repairs',
       'Board Up', 'Leak Detection', 'Sewage', 'Rain', 'Asbestos', 'Lead',
       'PREP Account', 'vp', 'City Program', 'Residentialray',
       'School District', 'W - Insured Concern', 'PS-Home Depot',
       'ASP Program Residential', 'Residential - DKI',
       '31330 Construction - Hazmat', 'Consulting',
       'Residential - Insurance ', 'storm damage', 'Global',
       'Schools - Colleges/University', 'IMACC Residential', 'Boise',
       'Parma/Wilder', 'Caldwell', 'Nampa', 'Emmett', 'Mountain Home',
       'McCall/Cascade', 'Payette', 'Owyhee County', 'Ontario  Oregon',
       'Other Misc Areas', '3', 'Sewage Backup', 'Hot Water Heater',
       'Roof Leak', 'Water Line', 'Toilet Overflow', 'Water Line Burst',
       'Rising Water', 'Fastest ', '31340 - Construction Remodel',
       'Customer Canceled', 'TCPN', 'Public works', 'Manufacturing',
       'Fire - Kitchen', 'Prop Mgmt Vendor Docs', 'ad', '6/1/16',
       'CAT - Residential ', 'Alpha & Omega', 'Hotel ',
       'Construction Management', 'SRM Large Commercial', 'Cat2',
       'N/A- Plumber Containment', 'N/A-PLUMBER Containment', 'N/A-PCON',
       'N/A-Containment', 'N/A- Containment', 'Plumber Containment',
       'N/A Plumber Containment', 'Not Applicable - Billing Plumber',
       'Contents', 'Nexxus Commercial', 'Direct Pay',
       'Project Management', 'Residential - Alacrity',
       'Single Family Residence', 'inu', 'T&M Preferred',
       'Residential-Rental', '11/24/2016', 'Commercial   ', 'Housewide',
       'Office', 'Commercial/ELE', 'Referral', 'Re', 'Steel Building',
       'Education - School', 'School Facility', 'Mult',
       'Restaurant Division', '3/2/18', 'Low Income',
       'W - Deficiency Issue', 'W - Insurance Company Concern',
       'W - Warranty Issue', 'W - Adjuster Concern',
       'W - Subtrade Supplier Vendor Non-Compliance', 'Residentialdki',
       'Residential loss ', 'reside', 'MSD', 'Merced-Res', 'Fresno-Res',
       '03162017', 'Resisdential', 'Hickam COM', 'House of Worship',
       'San Francisco-Res', 'Napa-Com', 'San Francisco-Com',
       '31200 Duct Cleaning', 'Cat Loss', 'Residential Cleaning Services',
       'Nationwide Program', 'cleaning', 'Non-Profit Organization',
       'Medical ', 'REB - Program TPAs', 'SHRA', 'Septic backup ',
       'Temporary Repair', 'Tenant', 'Cat 1', 'USA', '11/17/2015',
       "Residential'", 'City JOC', 'Comp Bid', 'Veri Claim',
       'Ventahood Fire', 'Fire - Emergency Service', 'Fire - Demolish',
       'builder', 'Furniture Restoration', 'Commercial - Condo',
       'Residential - Non Insurance'], dtype=object)

In [23]:
data_sub = data1.head(100000)

In [24]:
data_sub.head(2)

,LossYearMo,City,State,Zip,DivisionName,StartedFlag,DisplayName,CommOrRes,NoteCount,PhotoCount,JobCount,ClaimCount,EstimateTotal
3,201508,Fort Lauderdale,FL,33317,Reconstruction Assessment,1,Structural Repairs,Residential,9.0,2.0,1.0,1.0,0.0
4,201508,Fort Lauderdale,FL,33324,Reconstruction Assessment,1,Structural Repairs,Residential,5.0,1.0,1.0,1.0,0.0

In [25]:
data.columns

Index(['LossYearMo', 'City', 'State', 'Zip', 'DivisionName', 'StartedFlag',
       'LossType', 'DisplayName', 'CommOrRes', 'NoteCount', 'PhotoCount',
       'JobCount', 'ClaimCount', 'EstimateTotal'],
      dtype='object')

In [28]:
data_sub_dum = pd.get_dummies(data_sub, columns=['LossYearMo', 'City', 'State', 'Zip', 'DivisionName', 'StartedFlag', 'DisplayName', 'CommOrRes'])

In [27]:
data_sub_sparse = pd.get_dummies(data_sub, columns=['LossYearMo', 'City', 'State', 'Zip', 'DivisionName', 'StartedFlag', 'DisplayName', 'CommOrRes'], sparse=True)

In [18]:
data_sub_dum.describe()

,NoteCount,PhotoCount,JobCount,ClaimCount,EstimateTotal,LossYearMo_200101,LossYearMo_200401,LossYearMo_200402,LossYearMo_200805,LossYearMo_200806,...,CommOrRes_R,CommOrRes_Residential,CommOrRes_Residential,CommOrRes_Residential - Insurance,CommOrRes_Residential - Private,CommOrRes_Residential Large Loss,CommOrRes_School,CommOrRes_Schools,CommOrRes_Tenant Policy,CommOrRes_Water Damage
count,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.0000,10000.000000,10000.000000,10000.000000,10000.0000,...,10000.0000,10000.000000,10000.000000,10000.00000,10000.0000,10000.00000,10000.0000,10000.000000,10000.0000,10000.0000
mean,53.943300,20.392700,1.177600,1.034800,1.562056e+04,0.0001,0.000200,0.000200,0.000200,0.0001,...,0.0001,0.865000,0.018900,0.00180,0.0001,0.00070,0.0001,0.001700,0.0001,0.0001
std,231.271709,77.241825,0.903405,0.418816,7.129773e+04,0.0100,0.014141,0.014141,0.014141,0.0100,...,0.0100,0.341741,0.136179,0.04239,0.0100,0.02645,0.0100,0.041198,0.0100,0.0100
min,1.000000,0.000000,1.000000,0.000000,-1.289280e+03,0.0000,0.000000,0.000000,0.000000,0.0000,...,0.0000,0.000000,0.000000,0.00000,0.0000,0.00000,0.0000,0.000000,0.0000,0.0000
25%,3.000000,0.000000,1.000000,1.000000,0.000000e+00,0.0000,0.000000,0.000000,0.000000,0.0000,...,0.0000,1.000000,0.000000,0.00000,0.0000,0.00000,0.0000,0.000000,0.0000,0.0000
50%,8.000000,2.000000,1.000000,1.000000,0.000000e+00,0.0000,0.000000,0.000000,0.000000,0.0000,...,0.0000,1.000000,0.000000,0.00000,0.0000,0.00000,0.0000,0.000000,0.0000,0.0000
75%,30.000000,10.000000,1.000000,1.000000,7.204013e+03,0.0000,0.000000,0.000000,0.000000,0.0000,...,0.0000,1.000000,0.000000,0.00000,0.0000,0.00000,0.0000,0.000000,0.0000,0.0000
max,11363.000000,2156.000000,37.000000,12.000000,2.593705e+06,1.0000,1.000000,1.000000,1.000000,1.0000,...,1.0000,1.000000,1.000000,1.00000,1.0000,1.00000,1.0000,1.000000,1.0000,1.0000

In [17]:
data_sub_sparse.describe()

,NoteCount,PhotoCount,JobCount,ClaimCount,EstimateTotal,LossYearMo_200101,LossYearMo_200401,LossYearMo_200402,LossYearMo_200805,LossYearMo_200806,...,CommOrRes_R,CommOrRes_Residential,CommOrRes_Residential,CommOrRes_Residential - Insurance,CommOrRes_Residential - Private,CommOrRes_Residential Large Loss,CommOrRes_School,CommOrRes_Schools,CommOrRes_Tenant Policy,CommOrRes_Water Damage
count,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.0000,10000.000000,10000.000000,10000.000000,10000.0000,...,10000.0000,10000.000000,10000.000000,10000.00000,10000.0000,10000.00000,10000.0000,10000.000000,10000.0000,10000.0000
mean,53.943300,20.392700,1.177600,1.034800,1.562056e+04,0.0001,0.000200,0.000200,0.000200,0.0001,...,0.0001,0.865000,0.018900,0.00180,0.0001,0.00070,0.0001,0.001700,0.0001,0.0001
std,231.271709,77.241825,0.903405,0.418816,7.129773e+04,0.0100,0.014141,0.014141,0.014141,0.0100,...,0.0100,0.341741,0.136179,0.04239,0.0100,0.02645,0.0100,0.041198,0.0100,0.0100
min,1.000000,0.000000,1.000000,0.000000,-1.289280e+03,0.0000,0.000000,0.000000,0.000000,0.0000,...,0.0000,0.000000,0.000000,0.00000,0.0000,0.00000,0.0000,0.000000,0.0000,0.0000
25%,3.000000,0.000000,1.000000,1.000000,0.000000e+00,0.0000,0.000000,0.000000,0.000000,0.0000,...,0.0000,1.000000,0.000000,0.00000,0.0000,0.00000,0.0000,0.000000,0.0000,0.0000
50%,8.000000,2.000000,1.000000,1.000000,0.000000e+00,0.0000,0.000000,0.000000,0.000000,0.0000,...,0.0000,1.000000,0.000000,0.00000,0.0000,0.00000,0.0000,0.000000,0.0000,0.0000
75%,30.000000,10.000000,1.000000,1.000000,7.204013e+03,0.0000,0.000000,0.000000,0.000000,0.0000,...,0.0000,1.000000,0.000000,0.00000,0.0000,0.00000,0.0000,0.000000,0.0000,0.0000
max,11363.000000,2156.000000,37.000000,12.000000,2.593705e+06,1.0000,1.000000,1.000000,1.000000,1.0000,...,1.0000,1.000000,1.000000,1.00000,1.0000,1.00000,1.0000,1.000000,1.0000,1.0000

In [29]:
print ("Before one hot encoding")
print ("Number of rows and column: ", data_sub.shape)
print ("Total memory used: {} MB".format(round(data_sub.memory_usage().sum()/(1024*1024), 2)))

print ("\nAfter one hot encoding")
print ("Number of rows and column: ", data_sub_dum.shape)
print ("Total memory used: {} MB".format(round(data_sub_dum.memory_usage().sum()/(1024*1024), 2)))

# print ("\nAfter sparse implementation")
# print ("Number of rows and column: ", data_sub_sparse.shape)
# print ("Total memory used: {} MB".format(round(data_sub_sparse.memory_usage().sum()/(1024*1024), 2)))

Before one hot encoding
Number of rows and column:  (100000, 13)
Total memory used: 10.68 MB

After one hot encoding
Number of rows and column:  (100000, 59742)
Total memory used: 5701.54 MB