In [1]:
import pandas as pd

In [2]:
train_o = pd.read_pickle('train_insurance_2017_new.pkl')
valid_o = pd.read_pickle('valid_insurance_2017_new.pkl')

In [3]:
a = pd.concat([train_o,valid_o])

In [4]:
b = pd.read_csv('training_results.csv',index_col = 0)

In [5]:
ori = pd.read_csv('cleaned_insurance_data_with_year.csv',index_col = 0)

/home/ambuj/izenda_fullcycle/lib/python3.6/site-packages/numpy/lib/arraysetops.py:522: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [6]:
a.head()

,StartedFlag,NoteCount,PhotoCount,JobCount,ClaimCount,LossYearMo,NewEstimateTotal,State_0,State_AB,State_AK,...,CommOrRes_Vandalism,CommOrRes_Vehicle Impact,CommOrRes_Warranty Repair,CommOrRes_Water,CommOrRes_Water Damage,CommOrRes_Westfield MRP,CommOrRes_Wind,CommOrRes_Work Authorization,CommOrRes_Xactimate,CommOrRes_residential
index,,,,,,,,,,,,,,,,,,,,,
1128074,1,638.0,84.0,5.0,5.0,10,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1976028,0,5.0,0.0,1.0,1.0,11,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
477573,0,8.0,0.0,1.0,1.0,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1088328,1,12.0,3.0,1.0,1.0,10,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999197,1,210.0,3.0,1.0,1.0,10,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
b.head()

,DivisionName,DisplayName,State,CommOrRes,StartedFlag,NoteCount,PhotoCount,JobCount,ClaimCount,LossYearMo,NewEstimateTotal,probability,preds
index,,,,,,,,,,,,,
1128074,Structure,Default,TN,Residential,1,638.0,84.0,5.0,5.0,10,1,0.738400,1
1976028,Structural Repairs,Structural Repairs,IN,Residential,0,5.0,0.0,1.0,1.0,11,0,0.427899,0
477573,Water,Water Mitigation,CA,Residential,0,8.0,0.0,1.0,1.0,4,0,0.488004,0
1088328,Water Mitigation,Water Mitigation,NY,Residential,1,12.0,3.0,1.0,1.0,10,0,0.462228,0
999197,Emergency Services - Multiple Services,Default,NC,Residential,1,210.0,3.0,1.0,1.0,10,1,0.736861,1

In [8]:
ori[ori.index == 1128074]

,LossYearMo,City,State,Zip,DivisionName,StartedFlag,DisplayName,CommOrRes,NoteCount,PhotoCount,JobCount,ClaimCount,EstimateTotal,LossMo,LossYear
1128074,201610,MURFREESBORO,TN,37130,Structure,1,Default,Residential,638.0,84.0,5.0,5.0,144081.45,10,2016

In [9]:
from sklearn.metrics import accuracy_score

In [10]:
accuracy_score(b.NewEstimateTotal,b.preds)

0.7494426956985478