In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('northwind_data.csv',index_col=0)

In [3]:
def splitter(days):

    try:
        days = int(str(days).split(' ')[0])
    except:
        days = np.nan

    return days

In [4]:
df['req_days'] = pd.to_datetime(df.RequiredDate) - pd.to_datetime(df.OrderDate)
df['req_days'] = df.req_days.apply(splitter)

In [5]:
df

,CustomerID,EmployeeID:string,OrderDate,RequiredDate,ShippedDate,ShipVia:string,Freight,ShipCity,ShipPostalCode,ShipCountry,...,SupplierID_21,SupplierID_22,SupplierID_23,SupplierID_24,SupplierID_25,SupplierID_26,SupplierID_27,SupplierID_28,SupplierID_29,req_days
0,DELDG,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Reims,51100,France,...,0,0,0,0,0,0,0,0,0,28
1,DELDG,6,1996-07-05,1996-08-16,1996-07-10,1,11.61,Münster,44087,Germany,...,0,0,0,1,0,0,0,0,0,42
2,RETCL,4,1996-07-08,1996-08-05,1996-07-12,2,65.83,Rio de Janeiro,05454-876,Brazil,...,0,0,0,1,0,0,0,0,0,28
3,DELDG,3,1996-07-08,1996-08-05,1996-07-15,1,41.34,Lyon,69004,France,...,0,0,0,0,0,1,0,0,0,28
4,DELDG,4,1996-07-09,1996-08-06,1996-07-11,2,51.30,Charleroi,B-6000,Belgium,...,0,0,0,0,0,0,0,1,0,28
5,RETCL,3,1996-07-10,1996-07-24,1996-07-16,2,58.17,Rio de Janeiro,05454-876,Brazil,...,0,0,1,0,0,0,0,0,0,14
6,NATWR,5,1996-07-11,1996-08-08,1996-07-23,2,22.98,Bern,3012,Switzerland,...,0,0,0,0,1,0,0,0,0,28
7,DELDG,9,1996-07-12,1996-08-09,1996-07-15,3,148.33,Genève,1204,Switzerland,...,0,0,0,0,0,0,0,1,0,28
8,DELDG,3,1996-07-15,1996-08-12,1996-07-17,2,13.97,Resende,08737-363,Brazil,...,0,0,0,1,0,0,0,0,0,28
9,RETCL,4,1996-07-16,1996-08-13,1996-07-22,3,81.91,San Cristóbal,5022,Venezuela,...,0,0,0,0,0,0,0,0,0,28
10,NATWR,1,1996-07-17,1996-08-14,1996-07-23,1,140.51,Graz,8010,Austria,...,0,0,0,0,0,0,0,0,0,28
11,NATWR,4,1996-07-18,1996-08-15,1996-07-25,3,3.25,México D.F.,05022,Mexico,...,0,0,0,0,0,0,0,0,0,28
12,RETCL,4,1996-07-19,1996-08-16,1996-07-29,1,55.09,Köln,50739,Germany,...,0,0,0,0,0,1,0,0,1,28
13,RETCL,4,1996-07-19,1996-08-16,1996-07-30,2,3.05,Rio de Janeiro,02389-673,Brazil,...,0,0,0,0,0,0,0,0,0,28
14,RETCL,8,1996-07-22,1996-08-19,1996-07-25,3,48.29,Albuquerque,87110,USA,...,0,0,0,0,0,1,0,0,0,28
15,NATWR,9,1996-07-23,1996-08-20,1996-07-31,3,146.06,Graz,8010,Austria,...,0,0,0,0,0,0,0,0,0,28
16,NATWR,6,1996-07-24,1996-08-21,1996-08-23,3,3.67,Bräcke,S-844 67,Sweden,...,0,0,0,0,0,0,0,0,0,28
17,NATWR,2,1996-07-25,1996-08-22,1996-08-12,1,55.28,Strasbourg,67000,France,...,0,0,0,0,0,0,0,0,0,28
18,DELDG,3,1996-07-26,1996-09-06,1996-07-31,3,25.73,Oulu,90110,Finland,...,0,0,0,0,0,0,0,0,0,42
19,NATWR,4,1996-07-29,1996-08-26,1996-08-06,1,208.58,München,80805,Germany,...,0,0,1,0,0,0,0,1,0,28
20,RETCL,8,1996-07-30,1996-08-27,1996-08-02,3,66.29,Caracas,1081,Venezuela,...,0,0,0,0,0,0,0,0,0,28
21,DELDG,5,1996-07-31,1996-08-14,1996-08-09,1,4.56,Seattle,98124,USA,...,0,0,0,0,0,0,0,0,0,14
22,DELDG,1,1996-08-01,1996-08-29,1996-08-02,1,136.54,Oulu,90110,Finland,...,0,0,0,0,0,0,0,0,0,28
23,DELDG,6,1996-08-01,1996-08-29,1996-08-30,2,4.54,Lander,82520,USA,...,0,0,0,0,0,0,0,0,0,28
24,RETCL,6,1996-08-02,1996-08-30,1996-08-06,2,98.03,Albuquerque,87110,USA,...,0,0,0,0,0,0,0,0,0,28
25,RETCL,3,1996-08-05,1996-09-02,1996-08-12,3,76.07,Cunewalde,01307,Germany,...,0,0,1,0,0,0,0,0,0,28
26,DELDG,6,1996-08-06,1996-09-03,1996-08-16,1,6.01,Reims,51100,France,...,0,0,0,0,0,0,0,0,0,28
27,RETCL,1,1996-08-07,1996-09-04,1996-08-09,1,26.93,Bergamo,24100,Italy,...,0,0,0,0,0,0,0,1,0,28
28,DELDG,8,1996-08-08,1996-08-22,1996-08-14,3,13.84,México D.F.,05033,Mexico,...,0,0,0,0,0,0,0,0,0,14
29,RETCL,2,1996-08-09,1996-09-06,1996-08-13,3,125.77,Leipzig,04179,Germany,...,0,0,0,0,0,0,0,0,1,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,NATWR,7,1998-04-24,1998-05-22,1998-04-30,3,24.12,Tsawassen,T2F 8M4,Canada,...,0,0,0,0,0,0,0,0,0,28
801,RETCL,3,1998-04-24,1998-05-22,1998-05-04,1,8.34,Campinas,04876-786,Brazil,...,0,0,0,0,0,0,0,0,0,28
802,NATWR,8,1998-04-27,1998-05-25,1998-05-05,2,59.41,Bräcke,S-844 67,Sweden,...,0,0,1,0,0,0,0,0,0,28
803,RETCL,7,1998-04-27,1998-05-25,NaN,3,2.79,Toulouse,31000,France,...,0,0,0,0,0,0,0,0,0,28
804,RETCL,3,1998-04-27,1998-05-25,1998-05-01,1,67.26,Rio de Janeiro,05454-876,Brazil,...,0,0,0,0,0,0,0,0,1,28
805,RETCL,2,1998-04-27,1998-05-25,1998-04-29,2,53.05,Salzburg,5020,Austria,...,0,0,0,0,0,0,0,0,0,28
806,NATWR,8,1998-04-28,1998-05-26,NaN,1,0.33,Buenos Aires,1010,Argentina,...,0,0,0,0,0,0,0,0,0,28
807,RETCL,7,1998-04-28,1998-05-26,1998-05-05,2,120.92,San Cristóbal,5022,Venezuela,...,0,0,0,1,0,1,0,0,0,28
808,NATWR,8,1998-04-28,1998-05-12,1998-05-01,2,278.96,London,WX3 6FW,UK,...,0,0,0,0,1,0,0,1,0,14
809,RETCL,3,1998-04-29,1998-05-27,1998-05-01,3,4.13,London,SW7 1RZ,UK,...,0,0,0,0,0,0,0,0,0,28
810,NATWR,9,1998-04-29,1998-05-27,NaN,3,31.14,Mannheim,68306,Germany,...,0,0,0,0,0,0,0,1,1,28
811,RETCL,2,1998-04-29,1998-06-10,NaN,2,85.80,Rio de Janeiro,02389-890,Brazil,...,0,0,0,0,0,0,0,1,0,42
812,NATWR,2,1998-04-30,1998-05-28,1998-05-04,2,10.98,Torino,10100,Italy,...,0,0,0,0,0,0,0,1,0,28
813,RETCL,4,1998-04-30,1998-06-11,NaN,3,14.01,Eugene,97403,USA,...,0,0,0,0,0,0,0,1,0,42
814,RETCL,4,1998-04-30,1998-05-28,NaN,2,29.93,Reggio Emilia,42100,Italy,...,0,0,0,1,0,0,0,0,0,28
815,RETCL,3,1998-04-30,1998-05-28,1998-05-06,2,81.73,Cork,NaN,Ireland,...,0,0,0,0,0,0,0,0,0,28
816,DELDG,1,1998-05-01,1998-05-29,1998-05-04,1,30.09,Boise,83720,USA,...,0,0,0,1,1,0,0,0,0,28
817,RETCL,8,1998-05-01,1998-05-29,NaN,1,12.91,Barquisimeto,3508,Venezuela,...,0,0,0,0,1,0,0,0,0,28
818,DELDG,7,1998-05-01,1998-05-29,1998-05-04,2,44.72,Seattle,98124,USA,...,0,0,0,0,0,0,0,0,0,28
819,NATWR,1,1998-05-04,1998-05-18,1998-05-06,2,7.98,Aachen,52066,Germany,...,0,0,0,0,0,0,0,0,0,14
820,RETCL,8,1998-05-04,1998-06-01,NaN,2,81.75,Sao Paulo,05487-020,Brazil,...,0,0,0,0,0,0,0,0,0,28
821,DELDG,1,1998-05-04,1998-06-01,1998-05-06,2,15.67,México D.F.,05033,Mexico,...,0,0,0,0,0,0,0,0,0,28
822,RETCL,2,1998-05-05,1998-06-02,NaN,1,136.00,Frankfurt a.M.,60528,Germany,...,0,0,0,0,0,0,0,0,0,28
823,RETCL,1,1998-05-05,1998-06-02,NaN,1,0.93,Barquisimeto,3508,Venezuela,...,0,0,0,0,0,0,0,0,0,28
824,NATWR,4,1998-05-05,1998-06-02,NaN,2,258.64,Graz,8010,Austria,...,0,0,1,0,0,0,0,0,0,28
825,RETCL,2,1998-05-05,1998-06-02,NaN,2,24.95,México D.F.,05033,Mexico,...,0,0,0,0,0,0,0,0,0,28
826,DELDG,7,1998-05-06,1998-06-03,NaN,2,18.44,Kobenhavn,1734,Denmark,...,0,0,0,0,0,0,0,0,0,28
827,DELDG,8,1998-05-06,1998-06-03,NaN,2,6.19,Genève,1204,Switzerland,...,1,0,1,0,0,0,0,0,0,28
828,NATWR,4,1998-05-06,1998-06-03,NaN,2,38.28,Marseille,13008,France,...,0,0,0,0,0,0,0,0,0,28
829,RETCL,1,1998-05-06,1998-06-03,NaN,2,8.53,Albuquerque,87110,USA,...,1,0,0,1,1,0,0,1,0,28

In [6]:
df.drop(columns=['OrderDate','RequiredDate','ShippedDate','ShipCity','ShipPostalCode'],inplace=True)

In [7]:
df.to_csv('northwind_data_1.csv',index=False)

In [8]:
df.columns

Index(['CustomerID', 'EmployeeID:string', 'ShipVia:string', 'Freight',
       'ShipCountry', 'ProductID_1', 'ProductID_2', 'ProductID_3',
       'ProductID_4', 'ProductID_5',
       ...
       'SupplierID_21', 'SupplierID_22', 'SupplierID_23', 'SupplierID_24',
       'SupplierID_25', 'SupplierID_26', 'SupplierID_27', 'SupplierID_28',
       'SupplierID_29', 'req_days'],
      dtype='object', length=120)

In [9]:
df.Freight.mean()

78.2442048192771