In [4]:
import pandas as pd
import numpy as np
import nltk

In [5]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [6]:
PATH="C:\\Users\\Lenovo\\Desktop\\izenda\\estimate_total_new_data\\Izenda_data_thru_201712 ver4c.csv"

In [7]:
original = pd.read_csv(PATH)

c:\python3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (2,4,8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
original.describe()

,LossYearMo,StartedFlag,NoteCount,PhotoCount,JobCount,ClaimCount,EstimateTotal,Estimate_NetClaim,Estimate_MaterialSaleTax,Estimate_OverHead,Estimate_Profit,Estimate_PctOverhead,Estimate_PctProfit,Estimate_Deductible,Estimate_BaseSvcCharge,CleanAddressFranchisorID,CleanAddressContactID
count,1471001.000,1898445.000,1897219.000,1898445.000,1898445.000,1898445.000,1898445.000,1898445.000,1898445.000,1898445.000,1898445.000,1898445.000,1898445.000,1898445.000,1898445.000,1898445.000,1898445.000
mean,201629.311,0.451,172.737,37.325,1.008,0.993,91566.138,44564.337,207.860,1547.299,1433.923,10.526,8.560,225.224,11.273,8.252,534218.658
std,198.595,0.498,14368.802,269.558,0.122,0.088,11315996.575,1303840.740,8476.643,45614.169,46224.602,57.652,48.648,6176.272,637.002,6.384,301300.412
min,191602.000,0.000,1.000,0.000,1.000,0.000,-339932.600,-360488744.000,-29696.000,-15066.000,-15066.000,-1692.000,-1692.000,0.000,0.000,1.000,1.000
25%,201512.000,0.000,4.000,0.000,1.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,292919.000
50%,201704.000,0.000,12.000,2.000,1.000,1.000,285.000,318.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,5.000,501997.000
75%,201803.000,1.000,62.000,23.000,1.000,1.000,10892.190,10606.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,16.000,798278.000
max,204410.000,1.000,16405200.000,149121.000,35.000,9.000,12174319336.000,646163204.000,5588347.000,21789906.000,21789906.000,15300.000,15300.000,4200000.000,420300.000,17.000,1141548.000

In [9]:
original

,DisplayName,DivisionName,LossAddressZip,City,Zip,State,LossYearMo,StartedFlag,LossType,CommOrRes,...,Estimate_NetClaim,Estimate_MaterialSaleTax,Estimate_OverHead,Estimate_Profit,Estimate_PctOverhead,Estimate_PctProfit,Estimate_Deductible,Estimate_BaseSvcCharge,CleanAddressFranchisorID,CleanAddressContactID
0,Contents,Evans Textile Restoration,2,Emerald Isle,28594,NC,201809.000,0,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,70416
1,Contents,Evans Textile Restoration,2,Surf City,28445,NC,201809.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,70437
2,Contents,Evans Textile Restoration,2,Greenville,29611,SC,201811.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,71035
3,Contents,Evans Textile Restoration,2,Columbia,29206,SC,201812.000,0,NaN,Residential-Renter,...,0,0,0,0,0,0,0,0,7,71139
4,Contents,Evans Textile Restoration,3,Decatur,30030,GA,nan,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67625
5,Contents,Evans Textile Restoration,3,Lilburn,30047,GA,nan,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,70100
6,Contents,Evans Textile Restoration,3,Mc Donald,37353,TN,201706.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67547
7,Contents,Evans Textile Restoration,3,Clarksville,37042,TN,201803.000,0,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,66996
8,Contents,Evans Textile Restoration,3,Gadsden,35901,AL,201803.000,0,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,66932
9,Contents,Evans Textile Restoration,3,Lawrenceville,30043,GA,201803.000,0,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67018
10,Contents,Evans Textile Restoration,3,Knoxville,37922,TN,201804.000,0,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67015
11,Contents,Evans Textile Restoration,3,Knoxville,37922,TN,201804.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67019
12,Contents,Evans Textile Restoration,3,Walls,38680,MS,201804.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67349
13,Contents,Evans Textile Restoration,3,Alpharetta,30022,GA,201805.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67455
14,Contents,Evans Textile Restoration,3,Enterprise,36330,AL,201805.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67435
15,Contents,Evans Textile Restoration,3,La Vergne,37086,TN,201805.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67434
16,Contents,Evans Textile Restoration,3,Memphis,38128,TN,201805.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67408
17,Contents,Evans Textile Restoration,3,Oliver Springs,37840,TN,201805.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67315
18,Contents,Evans Textile Restoration,3,Birmingham,35208,AL,201806.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67619
19,Contents,Evans Textile Restoration,3,Chattanooga,37421,TN,201806.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67636
20,Contents,Evans Textile Restoration,3,Estill Springs,37330,TN,201806.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67603
21,Contents,Evans Textile Restoration,3,Holly Springs,38635,MS,201806.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67553
22,Contents,Evans Textile Restoration,3,Manchester,37355,TN,201806.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67654
23,Contents,Evans Textile Restoration,3,Marietta,30060,GA,201806.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67657
24,Contents,Evans Textile Restoration,3,Memphis,38111,TN,201806.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67569
25,Contents,Evans Textile Restoration,3,Ooltewah,37363,TN,201806.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67602
26,Contents,Evans Textile Restoration,3,Smyrna,37167,TN,201806.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,70280
27,Contents,Evans Textile Restoration,3,Winchester,37398,TN,201806.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67689
28,Contents,Evans Textile Restoration,3,Lawrenceville,30045,GA,201806.000,1,NaN,Residential-Renter,...,0,0,0,0,0,0,0,0,7,70128
29,Contents,Evans Textile Restoration,3,Alpharetta,30009,GA,201807.000,1,NaN,Residential-Homeowner,...,0,0,0,0,0,0,0,0,7,67675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1898415,Default,Wet Check,8,Boise,83705,ID,201408.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,2106
1898416,Default,Wet Check,8,Boise,83706,ID,201408.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,2818
1898417,Default,Wet Check,8,Boise,83706,ID,201408.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,2098
1898418,Default,Wet Check,8,Boise,83709,ID,201408.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,1992
1898419,Default,Wet Check,8,Boise,83713,ID,201408.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,1868
1898420,Default,Wet Check,8,Kuna,83634,ID,201408.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,1756
1898421,Default,Wet Check,8,Meridian,83642,ID,201408.000,0,NaN,Residential,...,2537,2,0,0,0,0,0,0,12,1799
1898422,Default,Wet Check,8,Meridian,83646,ID,201408.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,1608
1898423,Default,Wet Check,8,Nampa,83651,ID,201408.000,0,NaN,Residential,...,2073,0,0,0,0,0,0,0,12,1587
1898424,Default,Wet Check,8,Nampa,83687,ID,201408.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,1548
1898425,Default,Wet Check,8,New Plymouth,83655,ID,201408.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,1786
1898426,Default,Wet Check,8,Boise,83709,ID,201409.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,2777
1898427,Default,Wet Check,8,Boise,83713,ID,201409.000,0,NaN,Residential,...,1677,3,0,0,0,0,0,0,12,2269
1898428,Default,Wet Check,8,Boise,83714,ID,201409.000,0,NaN,Residential,...,71,0,0,0,0,0,0,0,12,2676
1898429,Default,Wet Check,8,Garden City,83714,ID,201409.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,3374
1898430,Default,Wet Check,8,Nampa,83651,ID,201409.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,2505
1898431,Default,Wet Check,8,Sweet,83670,ID,201409.000,0,NaN,Residential,...,3680,8,0,0,0,0,0,0,12,2669
1898432,Default,Wet Check,8,Boise,83709,ID,201409.000,1,NaN,Residential,...,0,0,0,0,0,0,0,0,12,2249
1898433,Default,Wet Check,8,Boise,83709,ID,201409.000,1,NaN,Residential,...,0,0,0,0,0,0,0,0,12,3405
1898434,Default,Wet Check,8,Eagle,83616,ID,201410.000,0,NaN,0,...,0,0,0,0,0,0,0,0,12,4910
1898435,Default,Wet Check,8,Garden City,83714,ID,201410.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,4082
1898436,Default,Wet Check,8,Meridian,83646,ID,201410.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,4213
1898437,Default,Wet Check,8,Boise,83705,ID,201411.000,0,NaN,0,...,0,0,0,0,0,0,0,0,12,4422
1898438,Default,Wet Check,8,Meridian,83642,ID,201411.000,0,NaN,0,...,0,0,0,0,0,0,0,0,12,4388
1898439,Default,Wet Check,8,Boise,83709,ID,201411.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,4382
1898440,Default,Wet Check,8,Meridian,83646,ID,201411.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,4669
1898441,Default,Wet Check,9,Port Angeles,98362,WA,201406.000,0,NaN,Residential,...,517,2,0,0,0,0,0,0,12,702
1898442,Default,Wet Check,9,Bellevue,98005,WA,201407.000,0,NaN,Residential,...,2677,4,0,0,0,0,0,0,12,1157
1898443,Default,Wet Check,9,Sacramento,95816,CA,201411.000,0,NaN,Residential,...,0,0,0,0,0,0,0,0,12,4617
1898444,Default,Wet Check,9,Ontario,97914,OR,201411.000,1,NaN,Residential,...,0,0,0,0,0,0,0,0,12,4616